# Generated by Django 3.1.7 on 2021-03-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublication',
            name='html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='historicalpublication',
            name='source',
            field=models.TextField(blank=True, default='title: Choose a good title\ndescription: Write a short description.\n\n## First paragraph\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...\n', help_text='You can use Markdown syntax.', verbose_name='source'),
        ),
        migrations.AddField(
            model_name='historicalpublication',
            name='toc',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='source',
            field=models.TextField(blank=True, default='title: Choose a good title\ndescription: Write a short description.\n\n## First paragraph\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...\n', help_text='You can use Markdown syntax.', verbose_name='source'),
        ),
        migrations.AddField(
            model_name='publication',
            name='toc',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
