"""
django-allauth settings.
https://django-allauth.readthedocs.io/en/latest/configuration.html
"""

ACCOUNT_ADAPTER = "accounts.adapter.CustomUserAccountAdapter"
# ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
ACCOUNT_AUTHENTICATION_METHOD = "username_email"  # Default: "username"
# ACCOUNT_CONFIRM_EMAIL_ON_GET = False
# ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = LOGIN_URL
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = (
    "/accounts/profile/"  # Default: None
)
# ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
# ACCOUNT_EMAIL_CONFIRMATION_HMAC = True
ACCOUNT_EMAIL_REQUIRED = True  # Default: False
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Default: optional
# ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Site] "
# ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"
# ACCOUNT_EMAIL_CONFIRMATION_COOLDOWN = 180
# ACCOUNT_EMAIL_MAX_LENGTH = 254
ACCOUNT_FORMS = {"signup": "accounts.forms.CustomSignupForm"}  # Default: {}
# ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 86400  # 1 day in seconds  # Default: 300
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True  # Default: False
# ACCOUNT_LOGOUT_ON_GET = False
# ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = False
# ACCOUNT_LOGIN_ON_PASSWORD_RESET = False
ACCOUNT_LOGOUT_REDIRECT_URL = "core:home"  # Default: "/"
# ACCOUNT_PASSWORD_INPUT_RENDER_VALUE = False
ACCOUNT_PRESERVE_USERNAME_CASING = False  # Default: True
# ACCOUNT_SESSION_REMEMBER = None
# ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = False
# ACCOUNT_SIGNUP_FORM_CLASS = None
# ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
# ACCOUNT_TEMPLATE_EXTENSION = "html"
# ACCOUNT_USERNAME_BLACKLIST = []
# ACCOUNT_UNIQUE_EMAIL = True
# ACCOUNT_USER_DISPLAY = user.username
# ACCOUNT_USER_MODEL_EMAIL_FIELD = "email"
# ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_USERNAME_MIN_LENGTH = 8  # Default: 1
# ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_USERNAME_VALIDATORS = "core.validators.username_validators"  # Default: None
# SOCIALACCOUNT_ADAPTER = "allauth.socialaccount.adapter.DefaultSocialAccountAdapter"
SOCIALACCOUNT_AUTO_SIGNUP = False  # Default: True
# SOCIALACCOUNT_EMAIL_VERIFICATION = ACCOUNT_EMAIL_VERIFICATION
# SOCIALACCOUNT_EMAIL_REQUIRED = ACCOUNT_EMAIL_REQUIRED
# SOCIALACCOUNT_FORMS = {}
# SOCIALACCOUNT_PROVIDERS = {}
# SOCIALACCOUNT_QUERY_EMAIL = ACCOUNT_EMAIL_REQUIRED
# SOCIALACCOUNT_STORE_TOKENS = True
